// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_register.proto

package com.roje.game.message.server_register;

public final class ServerRegister {
  private ServerRegister() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerRegRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerRegRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerRegResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerRegResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025server_register.proto\032\021server_info.pro" +
      "to\032\017conn_info.proto\"3\n\020ServerRegRequest\022" +
      "\037\n\nserverInfo\030\001 \001(\0132\013.ServerInfo\"u\n\021Serv" +
      "erRegResponse\022\017\n\007success\030\001 \001(\010\022\013\n\003msg\030\002 " +
      "\001(\t\022\n\n\002id\030\003 \001(\005\022\033\n\010gateInfo\030\004 \003(\0132\t.Conn" +
      "Info\022\031\n\004type\030\005 \001(\0162\013.ServerTypeB)\n%com.r" +
      "oje.game.message.server_registerP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.roje.game.message.server_info.ServerInfoOuterClass.getDescriptor(),
          com.roje.game.message.conn_info.ConnInfoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_ServerRegRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServerRegRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerRegRequest_descriptor,
        new java.lang.String[] { "ServerInfo", });
    internal_static_ServerRegResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ServerRegResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerRegResponse_descriptor,
        new java.lang.String[] { "Success", "Msg", "Id", "GateInfo", "Type", });
    com.roje.game.message.server_info.ServerInfoOuterClass.getDescriptor();
    com.roje.game.message.conn_info.ConnInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
