thread-config:
  custom-configs:
    - name: channel
      thread-size: 3
    - name: account
      thread-size: 3
  io-config:
    core-pool-size: 3
    maximum-pool-size: 10
    keep-alive-time: 30
    capacity: 100000
  sync-config:
    command-size: 100000
cluster-server:
  config:
    port: 8007
    so-back-log: 2048
    so-keep-alive: true
    tcp-no-delay: true
    reader-idle-time: 20
    writer-idle-time: 0
    all-idle-time: 0
    so-linger: 0
server:
  port: 8008
  servlet:
    context-path: /roje/cluster
spring:
  application:
    name: cluster-server
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    timeout: 3s
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0
