thread-config:
  io-core-pool-size: 10
  io-maximum-pool-size: 100
  io-keep-alive-time: 30
  io-capacity: 100000
  sync-name: sync
  sync-time-interval: 0
  sync-command-size: 100000
cluster-server:
  config:
    port: 8007
    so-back-log: 2048
    so-keep-alive: true
    tcp-no-delay: true
    reader-idle-time: 20
    writer-idle-time: 0
    all-idle-time: 0
    so-linger: 0
server:
  port: 8008
  servlet:
    context-path: /roje
spring:
  application:
    name: cluster-server
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    timeout: 3s
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0
