thread-config:
  io-core-pool-size: 10
  io-maximum-pool-size: 100
  io-keep-alive-time: 30
  io-capacity: 100000
  sync-name: sync
  sync-time-interval: 0
  sync-command-size: 100000
netty-cluster-tcp-server-config:
  port: 7000
  so-back-log: 2048
  so-keep-alive: true
  tcp-no-delay: true
  reader-idle-time: 20
  writer-idle-time: 0
  all-idle-time: 0
  so-linger: 0
netty-cluster-http-server-config:
  port: 7001
  so-back-log: 2048
  so-keep-alive: true
  tcp-no-delay: true
  so-linger: 0
server:
  info:
    name: cluster-server
    ip: 127.0.0.1
    inner-port: 7000
    http-port: 7001
    state: normal
    max-user-count: 1000
    type: cluster
    version-code: 1
    client-version-code: 0
