client:
  cluster:
    so-linger: 0
    reader-idle-time: 20
    writer-idle-time: 10
    all-idle-time: 10
    tcp-no-delay: true
    reconnect-time: 5
    connect-timeout: 2000
    ip: 127.0.0.1
    port: 8007
serverInfo:
  ip: 127.0.0.1
  port: 7001
  game-id: 1
  max-user-count: 1000
  name: 牛牛
  require-version: 0
game-server:
  config:
    port: 7000
    so-back-log: 1024
    so-keep-alive: true
    tcp-no-delay: true
    so-linger: 0
    reader-idle-time: 0
    writer-idle-time: 0
    all-idle-time: 0
spring:
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    timeout: 3s
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0
niuniu:
  max-create-count: 1
thread-config:
  single-thread-room-size: 5
  io-config:
    core-pool-size: 3
    maximum-pool-size: 10
    keep-alive-time: 30
    capacity: 100000
  sync-config:
    command-size: 100000
  custom-configs:
    - name: channel
      thread-size: 3
    - name: role
      thread-size: 3
