// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: golden-flaud.proto

package com.roje.game.message.nn;

/**
 * Protobuf type {@code GFCardRoomConfig}
 */
public  final class GFCardRoomConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GFCardRoomConfig)
    GFCardRoomConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GFCardRoomConfig.newBuilder() to construct.
  private GFCardRoomConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GFCardRoomConfig() {
    round_ = 0;
    payment_ = 0;
    person_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GFCardRoomConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            round_ = input.readInt32();
            break;
          }
          case 16: {

            payment_ = input.readInt32();
            break;
          }
          case 24: {

            person_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.roje.game.message.nn.GoldenFlaud.internal_static_GFCardRoomConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.roje.game.message.nn.GoldenFlaud.internal_static_GFCardRoomConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.roje.game.message.nn.GFCardRoomConfig.class, com.roje.game.message.nn.GFCardRoomConfig.Builder.class);
  }

  public static final int ROUND_FIELD_NUMBER = 1;
  private int round_;
  /**
   * <code>int32 round = 1;</code>
   */
  public int getRound() {
    return round_;
  }

  public static final int PAYMENT_FIELD_NUMBER = 2;
  private int payment_;
  /**
   * <code>int32 payment = 2;</code>
   */
  public int getPayment() {
    return payment_;
  }

  public static final int PERSON_FIELD_NUMBER = 3;
  private int person_;
  /**
   * <code>int32 person = 3;</code>
   */
  public int getPerson() {
    return person_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (round_ != 0) {
      output.writeInt32(1, round_);
    }
    if (payment_ != 0) {
      output.writeInt32(2, payment_);
    }
    if (person_ != 0) {
      output.writeInt32(3, person_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (round_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, round_);
    }
    if (payment_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, payment_);
    }
    if (person_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, person_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.roje.game.message.nn.GFCardRoomConfig)) {
      return super.equals(obj);
    }
    com.roje.game.message.nn.GFCardRoomConfig other = (com.roje.game.message.nn.GFCardRoomConfig) obj;

    boolean result = true;
    result = result && (getRound()
        == other.getRound());
    result = result && (getPayment()
        == other.getPayment());
    result = result && (getPerson()
        == other.getPerson());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROUND_FIELD_NUMBER;
    hash = (53 * hash) + getRound();
    hash = (37 * hash) + PAYMENT_FIELD_NUMBER;
    hash = (53 * hash) + getPayment();
    hash = (37 * hash) + PERSON_FIELD_NUMBER;
    hash = (53 * hash) + getPerson();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.roje.game.message.nn.GFCardRoomConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roje.game.message.nn.GFCardRoomConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roje.game.message.nn.GFCardRoomConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roje.game.message.nn.GFCardRoomConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roje.game.message.nn.GFCardRoomConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roje.game.message.nn.GFCardRoomConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roje.game.message.nn.GFCardRoomConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.roje.game.message.nn.GFCardRoomConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.roje.game.message.nn.GFCardRoomConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.roje.game.message.nn.GFCardRoomConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.roje.game.message.nn.GFCardRoomConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.roje.game.message.nn.GFCardRoomConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.roje.game.message.nn.GFCardRoomConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GFCardRoomConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GFCardRoomConfig)
      com.roje.game.message.nn.GFCardRoomConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.roje.game.message.nn.GoldenFlaud.internal_static_GFCardRoomConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.roje.game.message.nn.GoldenFlaud.internal_static_GFCardRoomConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.roje.game.message.nn.GFCardRoomConfig.class, com.roje.game.message.nn.GFCardRoomConfig.Builder.class);
    }

    // Construct using com.roje.game.message.nn.GFCardRoomConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      round_ = 0;

      payment_ = 0;

      person_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.roje.game.message.nn.GoldenFlaud.internal_static_GFCardRoomConfig_descriptor;
    }

    @java.lang.Override
    public com.roje.game.message.nn.GFCardRoomConfig getDefaultInstanceForType() {
      return com.roje.game.message.nn.GFCardRoomConfig.getDefaultInstance();
    }

    @java.lang.Override
    public com.roje.game.message.nn.GFCardRoomConfig build() {
      com.roje.game.message.nn.GFCardRoomConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.roje.game.message.nn.GFCardRoomConfig buildPartial() {
      com.roje.game.message.nn.GFCardRoomConfig result = new com.roje.game.message.nn.GFCardRoomConfig(this);
      result.round_ = round_;
      result.payment_ = payment_;
      result.person_ = person_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.roje.game.message.nn.GFCardRoomConfig) {
        return mergeFrom((com.roje.game.message.nn.GFCardRoomConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.roje.game.message.nn.GFCardRoomConfig other) {
      if (other == com.roje.game.message.nn.GFCardRoomConfig.getDefaultInstance()) return this;
      if (other.getRound() != 0) {
        setRound(other.getRound());
      }
      if (other.getPayment() != 0) {
        setPayment(other.getPayment());
      }
      if (other.getPerson() != 0) {
        setPerson(other.getPerson());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.roje.game.message.nn.GFCardRoomConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.roje.game.message.nn.GFCardRoomConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int round_ ;
    /**
     * <code>int32 round = 1;</code>
     */
    public int getRound() {
      return round_;
    }
    /**
     * <code>int32 round = 1;</code>
     */
    public Builder setRound(int value) {
      
      round_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 round = 1;</code>
     */
    public Builder clearRound() {
      
      round_ = 0;
      onChanged();
      return this;
    }

    private int payment_ ;
    /**
     * <code>int32 payment = 2;</code>
     */
    public int getPayment() {
      return payment_;
    }
    /**
     * <code>int32 payment = 2;</code>
     */
    public Builder setPayment(int value) {
      
      payment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 payment = 2;</code>
     */
    public Builder clearPayment() {
      
      payment_ = 0;
      onChanged();
      return this;
    }

    private int person_ ;
    /**
     * <code>int32 person = 3;</code>
     */
    public int getPerson() {
      return person_;
    }
    /**
     * <code>int32 person = 3;</code>
     */
    public Builder setPerson(int value) {
      
      person_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 person = 3;</code>
     */
    public Builder clearPerson() {
      
      person_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GFCardRoomConfig)
  }

  // @@protoc_insertion_point(class_scope:GFCardRoomConfig)
  private static final com.roje.game.message.nn.GFCardRoomConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.roje.game.message.nn.GFCardRoomConfig();
  }

  public static com.roje.game.message.nn.GFCardRoomConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GFCardRoomConfig>
      PARSER = new com.google.protobuf.AbstractParser<GFCardRoomConfig>() {
    @java.lang.Override
    public GFCardRoomConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GFCardRoomConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GFCardRoomConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GFCardRoomConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.roje.game.message.nn.GFCardRoomConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

