// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nn.proto

package com.roje.game.message.nn;

/**
 * Protobuf type {@code NiuNiuCardRoomConfig}
 */
public  final class NiuNiuCardRoomConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NiuNiuCardRoomConfig)
    NiuNiuCardRoomConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NiuNiuCardRoomConfig.newBuilder() to construct.
  private NiuNiuCardRoomConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NiuNiuCardRoomConfig() {
    mode_ = 0;
    baseScore_ = 0;
    round_ = 0;
    payMode_ = 0;
    startMode_ = 0;
    maxTui_ = 0;
    maxQiang_ = 0;
    doublingMode_ = 0;
    szn_ = false;
    whn_ = false;
    thn_ = false;
    hln_ = false;
    zdn_ = false;
    wxn_ = false;
    ths_ = false;
    fbEnterHalfWay_ = false;
    fbRub_ = false;
    ma_ = false;
    betDoubling_ = false;
    betLimit_ = false;
    joker_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NiuNiuCardRoomConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            mode_ = input.readInt32();
            break;
          }
          case 16: {

            baseScore_ = input.readInt32();
            break;
          }
          case 24: {

            round_ = input.readInt32();
            break;
          }
          case 32: {

            payMode_ = input.readInt32();
            break;
          }
          case 40: {

            startMode_ = input.readInt32();
            break;
          }
          case 48: {

            maxTui_ = input.readInt32();
            break;
          }
          case 56: {

            maxQiang_ = input.readInt32();
            break;
          }
          case 64: {

            doublingMode_ = input.readInt32();
            break;
          }
          case 72: {

            szn_ = input.readBool();
            break;
          }
          case 80: {

            whn_ = input.readBool();
            break;
          }
          case 88: {

            thn_ = input.readBool();
            break;
          }
          case 96: {

            hln_ = input.readBool();
            break;
          }
          case 104: {

            zdn_ = input.readBool();
            break;
          }
          case 112: {

            wxn_ = input.readBool();
            break;
          }
          case 120: {

            ths_ = input.readBool();
            break;
          }
          case 128: {

            fbEnterHalfWay_ = input.readBool();
            break;
          }
          case 136: {

            fbRub_ = input.readBool();
            break;
          }
          case 144: {

            ma_ = input.readBool();
            break;
          }
          case 152: {

            betDoubling_ = input.readBool();
            break;
          }
          case 160: {

            betLimit_ = input.readBool();
            break;
          }
          case 168: {

            joker_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.roje.game.message.nn.Nn.internal_static_NiuNiuCardRoomConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.roje.game.message.nn.Nn.internal_static_NiuNiuCardRoomConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.roje.game.message.nn.NiuNiuCardRoomConfig.class, com.roje.game.message.nn.NiuNiuCardRoomConfig.Builder.class);
  }

  public static final int MODE_FIELD_NUMBER = 1;
  private int mode_;
  /**
   * <code>int32 mode = 1;</code>
   */
  public int getMode() {
    return mode_;
  }

  public static final int BASESCORE_FIELD_NUMBER = 2;
  private int baseScore_;
  /**
   * <code>int32 baseScore = 2;</code>
   */
  public int getBaseScore() {
    return baseScore_;
  }

  public static final int ROUND_FIELD_NUMBER = 3;
  private int round_;
  /**
   * <code>int32 round = 3;</code>
   */
  public int getRound() {
    return round_;
  }

  public static final int PAYMODE_FIELD_NUMBER = 4;
  private int payMode_;
  /**
   * <code>int32 payMode = 4;</code>
   */
  public int getPayMode() {
    return payMode_;
  }

  public static final int STARTMODE_FIELD_NUMBER = 5;
  private int startMode_;
  /**
   * <code>int32 startMode = 5;</code>
   */
  public int getStartMode() {
    return startMode_;
  }

  public static final int MAXTUI_FIELD_NUMBER = 6;
  private int maxTui_;
  /**
   * <code>int32 maxTui = 6;</code>
   */
  public int getMaxTui() {
    return maxTui_;
  }

  public static final int MAXQIANG_FIELD_NUMBER = 7;
  private int maxQiang_;
  /**
   * <code>int32 maxQiang = 7;</code>
   */
  public int getMaxQiang() {
    return maxQiang_;
  }

  public static final int DOUBLINGMODE_FIELD_NUMBER = 8;
  private int doublingMode_;
  /**
   * <code>int32 doublingMode = 8;</code>
   */
  public int getDoublingMode() {
    return doublingMode_;
  }

  public static final int SZN_FIELD_NUMBER = 9;
  private boolean szn_;
  /**
   * <code>bool szn = 9;</code>
   */
  public boolean getSzn() {
    return szn_;
  }

  public static final int WHN_FIELD_NUMBER = 10;
  private boolean whn_;
  /**
   * <code>bool whn = 10;</code>
   */
  public boolean getWhn() {
    return whn_;
  }

  public static final int THN_FIELD_NUMBER = 11;
  private boolean thn_;
  /**
   * <code>bool thn = 11;</code>
   */
  public boolean getThn() {
    return thn_;
  }

  public static final int HLN_FIELD_NUMBER = 12;
  private boolean hln_;
  /**
   * <code>bool hln = 12;</code>
   */
  public boolean getHln() {
    return hln_;
  }

  public static final int ZDN_FIELD_NUMBER = 13;
  private boolean zdn_;
  /**
   * <code>bool zdn = 13;</code>
   */
  public boolean getZdn() {
    return zdn_;
  }

  public static final int WXN_FIELD_NUMBER = 14;
  private boolean wxn_;
  /**
   * <code>bool wxn = 14;</code>
   */
  public boolean getWxn() {
    return wxn_;
  }

  public static final int THS_FIELD_NUMBER = 15;
  private boolean ths_;
  /**
   * <code>bool ths = 15;</code>
   */
  public boolean getThs() {
    return ths_;
  }

  public static final int FB_ENTERHALFWAY_FIELD_NUMBER = 16;
  private boolean fbEnterHalfWay_;
  /**
   * <code>bool fb_enterHalfWay = 16;</code>
   */
  public boolean getFbEnterHalfWay() {
    return fbEnterHalfWay_;
  }

  public static final int FB_RUB_FIELD_NUMBER = 17;
  private boolean fbRub_;
  /**
   * <code>bool fb_rub = 17;</code>
   */
  public boolean getFbRub() {
    return fbRub_;
  }

  public static final int MA_FIELD_NUMBER = 18;
  private boolean ma_;
  /**
   * <code>bool ma = 18;</code>
   */
  public boolean getMa() {
    return ma_;
  }

  public static final int BET_DOUBLING_FIELD_NUMBER = 19;
  private boolean betDoubling_;
  /**
   * <code>bool bet_doubling = 19;</code>
   */
  public boolean getBetDoubling() {
    return betDoubling_;
  }

  public static final int BET_LIMIT_FIELD_NUMBER = 20;
  private boolean betLimit_;
  /**
   * <code>bool bet_limit = 20;</code>
   */
  public boolean getBetLimit() {
    return betLimit_;
  }

  public static final int JOKER_FIELD_NUMBER = 21;
  private boolean joker_;
  /**
   * <code>bool joker = 21;</code>
   */
  public boolean getJoker() {
    return joker_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mode_ != 0) {
      output.writeInt32(1, mode_);
    }
    if (baseScore_ != 0) {
      output.writeInt32(2, baseScore_);
    }
    if (round_ != 0) {
      output.writeInt32(3, round_);
    }
    if (payMode_ != 0) {
      output.writeInt32(4, payMode_);
    }
    if (startMode_ != 0) {
      output.writeInt32(5, startMode_);
    }
    if (maxTui_ != 0) {
      output.writeInt32(6, maxTui_);
    }
    if (maxQiang_ != 0) {
      output.writeInt32(7, maxQiang_);
    }
    if (doublingMode_ != 0) {
      output.writeInt32(8, doublingMode_);
    }
    if (szn_ != false) {
      output.writeBool(9, szn_);
    }
    if (whn_ != false) {
      output.writeBool(10, whn_);
    }
    if (thn_ != false) {
      output.writeBool(11, thn_);
    }
    if (hln_ != false) {
      output.writeBool(12, hln_);
    }
    if (zdn_ != false) {
      output.writeBool(13, zdn_);
    }
    if (wxn_ != false) {
      output.writeBool(14, wxn_);
    }
    if (ths_ != false) {
      output.writeBool(15, ths_);
    }
    if (fbEnterHalfWay_ != false) {
      output.writeBool(16, fbEnterHalfWay_);
    }
    if (fbRub_ != false) {
      output.writeBool(17, fbRub_);
    }
    if (ma_ != false) {
      output.writeBool(18, ma_);
    }
    if (betDoubling_ != false) {
      output.writeBool(19, betDoubling_);
    }
    if (betLimit_ != false) {
      output.writeBool(20, betLimit_);
    }
    if (joker_ != false) {
      output.writeBool(21, joker_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, mode_);
    }
    if (baseScore_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, baseScore_);
    }
    if (round_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, round_);
    }
    if (payMode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, payMode_);
    }
    if (startMode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, startMode_);
    }
    if (maxTui_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, maxTui_);
    }
    if (maxQiang_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, maxQiang_);
    }
    if (doublingMode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, doublingMode_);
    }
    if (szn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, szn_);
    }
    if (whn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, whn_);
    }
    if (thn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, thn_);
    }
    if (hln_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, hln_);
    }
    if (zdn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, zdn_);
    }
    if (wxn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, wxn_);
    }
    if (ths_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(15, ths_);
    }
    if (fbEnterHalfWay_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(16, fbEnterHalfWay_);
    }
    if (fbRub_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(17, fbRub_);
    }
    if (ma_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(18, ma_);
    }
    if (betDoubling_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(19, betDoubling_);
    }
    if (betLimit_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(20, betLimit_);
    }
    if (joker_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(21, joker_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.roje.game.message.nn.NiuNiuCardRoomConfig)) {
      return super.equals(obj);
    }
    com.roje.game.message.nn.NiuNiuCardRoomConfig other = (com.roje.game.message.nn.NiuNiuCardRoomConfig) obj;

    boolean result = true;
    result = result && (getMode()
        == other.getMode());
    result = result && (getBaseScore()
        == other.getBaseScore());
    result = result && (getRound()
        == other.getRound());
    result = result && (getPayMode()
        == other.getPayMode());
    result = result && (getStartMode()
        == other.getStartMode());
    result = result && (getMaxTui()
        == other.getMaxTui());
    result = result && (getMaxQiang()
        == other.getMaxQiang());
    result = result && (getDoublingMode()
        == other.getDoublingMode());
    result = result && (getSzn()
        == other.getSzn());
    result = result && (getWhn()
        == other.getWhn());
    result = result && (getThn()
        == other.getThn());
    result = result && (getHln()
        == other.getHln());
    result = result && (getZdn()
        == other.getZdn());
    result = result && (getWxn()
        == other.getWxn());
    result = result && (getThs()
        == other.getThs());
    result = result && (getFbEnterHalfWay()
        == other.getFbEnterHalfWay());
    result = result && (getFbRub()
        == other.getFbRub());
    result = result && (getMa()
        == other.getMa());
    result = result && (getBetDoubling()
        == other.getBetDoubling());
    result = result && (getBetLimit()
        == other.getBetLimit());
    result = result && (getJoker()
        == other.getJoker());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODE_FIELD_NUMBER;
    hash = (53 * hash) + getMode();
    hash = (37 * hash) + BASESCORE_FIELD_NUMBER;
    hash = (53 * hash) + getBaseScore();
    hash = (37 * hash) + ROUND_FIELD_NUMBER;
    hash = (53 * hash) + getRound();
    hash = (37 * hash) + PAYMODE_FIELD_NUMBER;
    hash = (53 * hash) + getPayMode();
    hash = (37 * hash) + STARTMODE_FIELD_NUMBER;
    hash = (53 * hash) + getStartMode();
    hash = (37 * hash) + MAXTUI_FIELD_NUMBER;
    hash = (53 * hash) + getMaxTui();
    hash = (37 * hash) + MAXQIANG_FIELD_NUMBER;
    hash = (53 * hash) + getMaxQiang();
    hash = (37 * hash) + DOUBLINGMODE_FIELD_NUMBER;
    hash = (53 * hash) + getDoublingMode();
    hash = (37 * hash) + SZN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSzn());
    hash = (37 * hash) + WHN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWhn());
    hash = (37 * hash) + THN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getThn());
    hash = (37 * hash) + HLN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHln());
    hash = (37 * hash) + ZDN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getZdn());
    hash = (37 * hash) + WXN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWxn());
    hash = (37 * hash) + THS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getThs());
    hash = (37 * hash) + FB_ENTERHALFWAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFbEnterHalfWay());
    hash = (37 * hash) + FB_RUB_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFbRub());
    hash = (37 * hash) + MA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMa());
    hash = (37 * hash) + BET_DOUBLING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBetDoubling());
    hash = (37 * hash) + BET_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBetLimit());
    hash = (37 * hash) + JOKER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getJoker());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.roje.game.message.nn.NiuNiuCardRoomConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.roje.game.message.nn.NiuNiuCardRoomConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NiuNiuCardRoomConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NiuNiuCardRoomConfig)
      com.roje.game.message.nn.NiuNiuCardRoomConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.roje.game.message.nn.Nn.internal_static_NiuNiuCardRoomConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.roje.game.message.nn.Nn.internal_static_NiuNiuCardRoomConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.roje.game.message.nn.NiuNiuCardRoomConfig.class, com.roje.game.message.nn.NiuNiuCardRoomConfig.Builder.class);
    }

    // Construct using com.roje.game.message.nn.NiuNiuCardRoomConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      mode_ = 0;

      baseScore_ = 0;

      round_ = 0;

      payMode_ = 0;

      startMode_ = 0;

      maxTui_ = 0;

      maxQiang_ = 0;

      doublingMode_ = 0;

      szn_ = false;

      whn_ = false;

      thn_ = false;

      hln_ = false;

      zdn_ = false;

      wxn_ = false;

      ths_ = false;

      fbEnterHalfWay_ = false;

      fbRub_ = false;

      ma_ = false;

      betDoubling_ = false;

      betLimit_ = false;

      joker_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.roje.game.message.nn.Nn.internal_static_NiuNiuCardRoomConfig_descriptor;
    }

    @java.lang.Override
    public com.roje.game.message.nn.NiuNiuCardRoomConfig getDefaultInstanceForType() {
      return com.roje.game.message.nn.NiuNiuCardRoomConfig.getDefaultInstance();
    }

    @java.lang.Override
    public com.roje.game.message.nn.NiuNiuCardRoomConfig build() {
      com.roje.game.message.nn.NiuNiuCardRoomConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.roje.game.message.nn.NiuNiuCardRoomConfig buildPartial() {
      com.roje.game.message.nn.NiuNiuCardRoomConfig result = new com.roje.game.message.nn.NiuNiuCardRoomConfig(this);
      result.mode_ = mode_;
      result.baseScore_ = baseScore_;
      result.round_ = round_;
      result.payMode_ = payMode_;
      result.startMode_ = startMode_;
      result.maxTui_ = maxTui_;
      result.maxQiang_ = maxQiang_;
      result.doublingMode_ = doublingMode_;
      result.szn_ = szn_;
      result.whn_ = whn_;
      result.thn_ = thn_;
      result.hln_ = hln_;
      result.zdn_ = zdn_;
      result.wxn_ = wxn_;
      result.ths_ = ths_;
      result.fbEnterHalfWay_ = fbEnterHalfWay_;
      result.fbRub_ = fbRub_;
      result.ma_ = ma_;
      result.betDoubling_ = betDoubling_;
      result.betLimit_ = betLimit_;
      result.joker_ = joker_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.roje.game.message.nn.NiuNiuCardRoomConfig) {
        return mergeFrom((com.roje.game.message.nn.NiuNiuCardRoomConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.roje.game.message.nn.NiuNiuCardRoomConfig other) {
      if (other == com.roje.game.message.nn.NiuNiuCardRoomConfig.getDefaultInstance()) return this;
      if (other.getMode() != 0) {
        setMode(other.getMode());
      }
      if (other.getBaseScore() != 0) {
        setBaseScore(other.getBaseScore());
      }
      if (other.getRound() != 0) {
        setRound(other.getRound());
      }
      if (other.getPayMode() != 0) {
        setPayMode(other.getPayMode());
      }
      if (other.getStartMode() != 0) {
        setStartMode(other.getStartMode());
      }
      if (other.getMaxTui() != 0) {
        setMaxTui(other.getMaxTui());
      }
      if (other.getMaxQiang() != 0) {
        setMaxQiang(other.getMaxQiang());
      }
      if (other.getDoublingMode() != 0) {
        setDoublingMode(other.getDoublingMode());
      }
      if (other.getSzn() != false) {
        setSzn(other.getSzn());
      }
      if (other.getWhn() != false) {
        setWhn(other.getWhn());
      }
      if (other.getThn() != false) {
        setThn(other.getThn());
      }
      if (other.getHln() != false) {
        setHln(other.getHln());
      }
      if (other.getZdn() != false) {
        setZdn(other.getZdn());
      }
      if (other.getWxn() != false) {
        setWxn(other.getWxn());
      }
      if (other.getThs() != false) {
        setThs(other.getThs());
      }
      if (other.getFbEnterHalfWay() != false) {
        setFbEnterHalfWay(other.getFbEnterHalfWay());
      }
      if (other.getFbRub() != false) {
        setFbRub(other.getFbRub());
      }
      if (other.getMa() != false) {
        setMa(other.getMa());
      }
      if (other.getBetDoubling() != false) {
        setBetDoubling(other.getBetDoubling());
      }
      if (other.getBetLimit() != false) {
        setBetLimit(other.getBetLimit());
      }
      if (other.getJoker() != false) {
        setJoker(other.getJoker());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.roje.game.message.nn.NiuNiuCardRoomConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.roje.game.message.nn.NiuNiuCardRoomConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int mode_ ;
    /**
     * <code>int32 mode = 1;</code>
     */
    public int getMode() {
      return mode_;
    }
    /**
     * <code>int32 mode = 1;</code>
     */
    public Builder setMode(int value) {
      
      mode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 mode = 1;</code>
     */
    public Builder clearMode() {
      
      mode_ = 0;
      onChanged();
      return this;
    }

    private int baseScore_ ;
    /**
     * <code>int32 baseScore = 2;</code>
     */
    public int getBaseScore() {
      return baseScore_;
    }
    /**
     * <code>int32 baseScore = 2;</code>
     */
    public Builder setBaseScore(int value) {
      
      baseScore_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 baseScore = 2;</code>
     */
    public Builder clearBaseScore() {
      
      baseScore_ = 0;
      onChanged();
      return this;
    }

    private int round_ ;
    /**
     * <code>int32 round = 3;</code>
     */
    public int getRound() {
      return round_;
    }
    /**
     * <code>int32 round = 3;</code>
     */
    public Builder setRound(int value) {
      
      round_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 round = 3;</code>
     */
    public Builder clearRound() {
      
      round_ = 0;
      onChanged();
      return this;
    }

    private int payMode_ ;
    /**
     * <code>int32 payMode = 4;</code>
     */
    public int getPayMode() {
      return payMode_;
    }
    /**
     * <code>int32 payMode = 4;</code>
     */
    public Builder setPayMode(int value) {
      
      payMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 payMode = 4;</code>
     */
    public Builder clearPayMode() {
      
      payMode_ = 0;
      onChanged();
      return this;
    }

    private int startMode_ ;
    /**
     * <code>int32 startMode = 5;</code>
     */
    public int getStartMode() {
      return startMode_;
    }
    /**
     * <code>int32 startMode = 5;</code>
     */
    public Builder setStartMode(int value) {
      
      startMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 startMode = 5;</code>
     */
    public Builder clearStartMode() {
      
      startMode_ = 0;
      onChanged();
      return this;
    }

    private int maxTui_ ;
    /**
     * <code>int32 maxTui = 6;</code>
     */
    public int getMaxTui() {
      return maxTui_;
    }
    /**
     * <code>int32 maxTui = 6;</code>
     */
    public Builder setMaxTui(int value) {
      
      maxTui_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maxTui = 6;</code>
     */
    public Builder clearMaxTui() {
      
      maxTui_ = 0;
      onChanged();
      return this;
    }

    private int maxQiang_ ;
    /**
     * <code>int32 maxQiang = 7;</code>
     */
    public int getMaxQiang() {
      return maxQiang_;
    }
    /**
     * <code>int32 maxQiang = 7;</code>
     */
    public Builder setMaxQiang(int value) {
      
      maxQiang_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maxQiang = 7;</code>
     */
    public Builder clearMaxQiang() {
      
      maxQiang_ = 0;
      onChanged();
      return this;
    }

    private int doublingMode_ ;
    /**
     * <code>int32 doublingMode = 8;</code>
     */
    public int getDoublingMode() {
      return doublingMode_;
    }
    /**
     * <code>int32 doublingMode = 8;</code>
     */
    public Builder setDoublingMode(int value) {
      
      doublingMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 doublingMode = 8;</code>
     */
    public Builder clearDoublingMode() {
      
      doublingMode_ = 0;
      onChanged();
      return this;
    }

    private boolean szn_ ;
    /**
     * <code>bool szn = 9;</code>
     */
    public boolean getSzn() {
      return szn_;
    }
    /**
     * <code>bool szn = 9;</code>
     */
    public Builder setSzn(boolean value) {
      
      szn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool szn = 9;</code>
     */
    public Builder clearSzn() {
      
      szn_ = false;
      onChanged();
      return this;
    }

    private boolean whn_ ;
    /**
     * <code>bool whn = 10;</code>
     */
    public boolean getWhn() {
      return whn_;
    }
    /**
     * <code>bool whn = 10;</code>
     */
    public Builder setWhn(boolean value) {
      
      whn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool whn = 10;</code>
     */
    public Builder clearWhn() {
      
      whn_ = false;
      onChanged();
      return this;
    }

    private boolean thn_ ;
    /**
     * <code>bool thn = 11;</code>
     */
    public boolean getThn() {
      return thn_;
    }
    /**
     * <code>bool thn = 11;</code>
     */
    public Builder setThn(boolean value) {
      
      thn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool thn = 11;</code>
     */
    public Builder clearThn() {
      
      thn_ = false;
      onChanged();
      return this;
    }

    private boolean hln_ ;
    /**
     * <code>bool hln = 12;</code>
     */
    public boolean getHln() {
      return hln_;
    }
    /**
     * <code>bool hln = 12;</code>
     */
    public Builder setHln(boolean value) {
      
      hln_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hln = 12;</code>
     */
    public Builder clearHln() {
      
      hln_ = false;
      onChanged();
      return this;
    }

    private boolean zdn_ ;
    /**
     * <code>bool zdn = 13;</code>
     */
    public boolean getZdn() {
      return zdn_;
    }
    /**
     * <code>bool zdn = 13;</code>
     */
    public Builder setZdn(boolean value) {
      
      zdn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool zdn = 13;</code>
     */
    public Builder clearZdn() {
      
      zdn_ = false;
      onChanged();
      return this;
    }

    private boolean wxn_ ;
    /**
     * <code>bool wxn = 14;</code>
     */
    public boolean getWxn() {
      return wxn_;
    }
    /**
     * <code>bool wxn = 14;</code>
     */
    public Builder setWxn(boolean value) {
      
      wxn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool wxn = 14;</code>
     */
    public Builder clearWxn() {
      
      wxn_ = false;
      onChanged();
      return this;
    }

    private boolean ths_ ;
    /**
     * <code>bool ths = 15;</code>
     */
    public boolean getThs() {
      return ths_;
    }
    /**
     * <code>bool ths = 15;</code>
     */
    public Builder setThs(boolean value) {
      
      ths_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool ths = 15;</code>
     */
    public Builder clearThs() {
      
      ths_ = false;
      onChanged();
      return this;
    }

    private boolean fbEnterHalfWay_ ;
    /**
     * <code>bool fb_enterHalfWay = 16;</code>
     */
    public boolean getFbEnterHalfWay() {
      return fbEnterHalfWay_;
    }
    /**
     * <code>bool fb_enterHalfWay = 16;</code>
     */
    public Builder setFbEnterHalfWay(boolean value) {
      
      fbEnterHalfWay_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool fb_enterHalfWay = 16;</code>
     */
    public Builder clearFbEnterHalfWay() {
      
      fbEnterHalfWay_ = false;
      onChanged();
      return this;
    }

    private boolean fbRub_ ;
    /**
     * <code>bool fb_rub = 17;</code>
     */
    public boolean getFbRub() {
      return fbRub_;
    }
    /**
     * <code>bool fb_rub = 17;</code>
     */
    public Builder setFbRub(boolean value) {
      
      fbRub_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool fb_rub = 17;</code>
     */
    public Builder clearFbRub() {
      
      fbRub_ = false;
      onChanged();
      return this;
    }

    private boolean ma_ ;
    /**
     * <code>bool ma = 18;</code>
     */
    public boolean getMa() {
      return ma_;
    }
    /**
     * <code>bool ma = 18;</code>
     */
    public Builder setMa(boolean value) {
      
      ma_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool ma = 18;</code>
     */
    public Builder clearMa() {
      
      ma_ = false;
      onChanged();
      return this;
    }

    private boolean betDoubling_ ;
    /**
     * <code>bool bet_doubling = 19;</code>
     */
    public boolean getBetDoubling() {
      return betDoubling_;
    }
    /**
     * <code>bool bet_doubling = 19;</code>
     */
    public Builder setBetDoubling(boolean value) {
      
      betDoubling_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool bet_doubling = 19;</code>
     */
    public Builder clearBetDoubling() {
      
      betDoubling_ = false;
      onChanged();
      return this;
    }

    private boolean betLimit_ ;
    /**
     * <code>bool bet_limit = 20;</code>
     */
    public boolean getBetLimit() {
      return betLimit_;
    }
    /**
     * <code>bool bet_limit = 20;</code>
     */
    public Builder setBetLimit(boolean value) {
      
      betLimit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool bet_limit = 20;</code>
     */
    public Builder clearBetLimit() {
      
      betLimit_ = false;
      onChanged();
      return this;
    }

    private boolean joker_ ;
    /**
     * <code>bool joker = 21;</code>
     */
    public boolean getJoker() {
      return joker_;
    }
    /**
     * <code>bool joker = 21;</code>
     */
    public Builder setJoker(boolean value) {
      
      joker_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool joker = 21;</code>
     */
    public Builder clearJoker() {
      
      joker_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NiuNiuCardRoomConfig)
  }

  // @@protoc_insertion_point(class_scope:NiuNiuCardRoomConfig)
  private static final com.roje.game.message.nn.NiuNiuCardRoomConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.roje.game.message.nn.NiuNiuCardRoomConfig();
  }

  public static com.roje.game.message.nn.NiuNiuCardRoomConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NiuNiuCardRoomConfig>
      PARSER = new com.google.protobuf.AbstractParser<NiuNiuCardRoomConfig>() {
    @java.lang.Override
    public NiuNiuCardRoomConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NiuNiuCardRoomConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NiuNiuCardRoomConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NiuNiuCardRoomConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.roje.game.message.nn.NiuNiuCardRoomConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

