thread-config:
  io-corePoolSize: 10
  io-maximumPoolSize: 100
  io-keepAliveTime: 30
  io-capacity: 100000
  sync-name: sync
  sync-timeInterval: 0
  sync-commandSize: 100000
netty:
  config:
    gate-game-tcp:
      soBackLog: 2048
      soKeepAlive: true
      tcpNoDelay: true
      readerIdleTime: 20
      writerIdleTime: 0
      allIdleTime: 0
      soLinger: 0
    gate-user-tcp:
      soBackLog: 2048
      soKeepAlive: true
      tcpNoDelay: true
      readerIdleTime: 20
      writerIdleTime: 0
      allIdleTime: 0
      soLinger: 0
netty-conn-cluster-client:
  so-linger: 0
  reader-idle-time: 20
  writer-idle-time: 10
  all-idle-time: 10
  tcp-no-delay: true
  reconnect-time: 5
  connect-timeout: 10
  cluster-ip: 127.0.0.1
  cluster-port: 7000
server:
  info:
    name: gate-server
    ip: 127.0.0.1
    user-port: 8088
    inner-port: 8089
    http-port: 8087
    state: normal
    max-user-count: 1000
    type: gate
    version-code: 1
    client-version-code: 0