// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package com.roje.game.message.create_room;

public interface ChangePosRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChangePosRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 applicantId = 1;</code>
   */
  long getApplicantId();
}
