// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package com.roje.game.message.create_room;

public interface CreateCardRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateCardRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 gameId = 1;</code>
   */
  int getGameId();

  /**
   * <code>.google.protobuf.Any config = 2;</code>
   */
  boolean hasConfig();
  /**
   * <code>.google.protobuf.Any config = 2;</code>
   */
  com.google.protobuf.Any getConfig();
  /**
   * <code>.google.protobuf.Any config = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getConfigOrBuilder();
}
