// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package com.roje.game.message.create_room;

public interface CreateCardRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateCardRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.google.protobuf.Any responseData = 3;</code>
   */
  boolean hasResponseData();
  /**
   * <code>.google.protobuf.Any responseData = 3;</code>
   */
  com.google.protobuf.Any getResponseData();
  /**
   * <code>.google.protobuf.Any responseData = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getResponseDataOrBuilder();

  /**
   * <code>string account = 4;</code>
   */
  java.lang.String getAccount();
  /**
   * <code>string account = 4;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>int32 type = 5;</code>
   */
  int getType();
}
