// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package com.roje.game.message.create_room;

public interface SitResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SitResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 seat = 1;</code>
   */
  int getSeat();
}
