// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_update.proto

package com.roje.game.message.server_update;

public interface ServerUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
