// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_info.proto

package com.roje.game.message.server_info;

public final class ServerInfoOuterClass {
  private ServerInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021server_info.proto\"\307\002\n\nServerInfo\022\n\n\002id" +
      "\030\001 \001(\005\022\n\n\002ip\030\002 \001(\t\022\031\n\004type\030\003 \001(\0162\013.Serve" +
      "rType\022\021\n\tinnerPort\030\004 \001(\005\022\034\n\005state\030\005 \001(\0162" +
      "\r.ServerStatus\022\016\n\006online\030\006 \001(\005\022\024\n\014maxUse" +
      "rCount\030\007 \001(\005\022\020\n\010httpport\030\010 \001(\005\022\014\n\004name\030\t" +
      " \001(\t\022\r\n\005wwwip\030\n \001(\t\022\022\n\nfreeMemory\030\013 \001(\005\022" +
      "\023\n\013totalMemory\030\014 \001(\005\022\017\n\007version\030\r \001(\005\022\034\n" +
      "\024requireClientVersion\030\016 \001(\005\022\026\n\016connected" +
      "Count\030\017 \001(\005\022\020\n\010userPort\030\020 \001(\005*D\n\nServerT" +
      "ype\022\013\n\007Unknown\020\000\022\013\n\007Cluster\020\001\022\010\n\004Gate\020\002\022" +
      "\010\n\004Hall\020\003\022\010\n\004Game\020\004*(\n\014ServerStatus\022\n\n\006N" +
      "ormal\020\000\022\014\n\010Maintain\020\001B%\n!com.roje.game.m" +
      "essage.server_infoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ServerInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerInfo_descriptor,
        new java.lang.String[] { "Id", "Ip", "Type", "InnerPort", "State", "Online", "MaxUserCount", "Httpport", "Name", "Wwwip", "FreeMemory", "TotalMemory", "Version", "RequireClientVersion", "ConnectedCount", "UserPort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
