// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action.proto

package com.roje.game.message.action;

public final class ActionOuterClass {
  private ActionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014action.proto*\244\002\n\006Action\022\010\n\004snap\020\000\022\017\n\nS" +
      "ervRegReq\020\351\007\022\017\n\nServRegRes\020\352\007\022\020\n\013ServInf" +
      "oReq\020\353\007\022\020\n\013ServInfoRes\020\354\007\022\r\n\010LoginReq\020\221N" +
      "\022\r\n\010loginRes\020\222N\022\027\n\021CreateCardRoomReq\020\241\234\001" +
      "\022\027\n\021CreateCardRoomRes\020\242\234\001\022\022\n\014EntryRoomRe" +
      "q\020\243\234\001\022\022\n\014EntryRoomRes\020\244\234\001\022\014\n\006SitReq\020\245\234\001\022" +
      "\014\n\006SitRes\020\246\234\001\022\022\n\014ChangePosReq\020\247\234\001\022\022\n\014Cha" +
      "ngePosRes\020\250\234\001\022\016\n\010ErrorRes\020\261\352\001B \n\034com.roj" +
      "e.game.message.actionP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
