// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action.proto

package com.roje.game.message.action;

/**
 * Protobuf enum {@code Action}
 */
public enum Action
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>snap = 0;</code>
   */
  snap(0),
  /**
   * <code>ServRegReq = 1001;</code>
   */
  ServRegReq(1001),
  /**
   * <code>ServRegRes = 1002;</code>
   */
  ServRegRes(1002),
  /**
   * <code>ServInfoReq = 1003;</code>
   */
  ServInfoReq(1003),
  /**
   * <code>ServInfoRes = 1004;</code>
   */
  ServInfoRes(1004),
  /**
   * <code>LoginReq = 10001;</code>
   */
  LoginReq(10001),
  /**
   * <code>loginRes = 10002;</code>
   */
  loginRes(10002),
  /**
   * <code>CreateCardRoomReq = 20001;</code>
   */
  CreateCardRoomReq(20001),
  /**
   * <code>CreateCardRoomRes = 20002;</code>
   */
  CreateCardRoomRes(20002),
  /**
   * <code>EntryRoomReq = 20003;</code>
   */
  EntryRoomReq(20003),
  /**
   * <code>EntryRoomRes = 20004;</code>
   */
  EntryRoomRes(20004),
  /**
   * <code>ErrorResponse = 30001;</code>
   */
  ErrorResponse(30001),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>snap = 0;</code>
   */
  public static final int snap_VALUE = 0;
  /**
   * <code>ServRegReq = 1001;</code>
   */
  public static final int ServRegReq_VALUE = 1001;
  /**
   * <code>ServRegRes = 1002;</code>
   */
  public static final int ServRegRes_VALUE = 1002;
  /**
   * <code>ServInfoReq = 1003;</code>
   */
  public static final int ServInfoReq_VALUE = 1003;
  /**
   * <code>ServInfoRes = 1004;</code>
   */
  public static final int ServInfoRes_VALUE = 1004;
  /**
   * <code>LoginReq = 10001;</code>
   */
  public static final int LoginReq_VALUE = 10001;
  /**
   * <code>loginRes = 10002;</code>
   */
  public static final int loginRes_VALUE = 10002;
  /**
   * <code>CreateCardRoomReq = 20001;</code>
   */
  public static final int CreateCardRoomReq_VALUE = 20001;
  /**
   * <code>CreateCardRoomRes = 20002;</code>
   */
  public static final int CreateCardRoomRes_VALUE = 20002;
  /**
   * <code>EntryRoomReq = 20003;</code>
   */
  public static final int EntryRoomReq_VALUE = 20003;
  /**
   * <code>EntryRoomRes = 20004;</code>
   */
  public static final int EntryRoomRes_VALUE = 20004;
  /**
   * <code>ErrorResponse = 30001;</code>
   */
  public static final int ErrorResponse_VALUE = 30001;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Action valueOf(int value) {
    return forNumber(value);
  }

  public static Action forNumber(int value) {
    switch (value) {
      case 0: return snap;
      case 1001: return ServRegReq;
      case 1002: return ServRegRes;
      case 1003: return ServInfoReq;
      case 1004: return ServInfoRes;
      case 10001: return LoginReq;
      case 10002: return loginRes;
      case 20001: return CreateCardRoomReq;
      case 20002: return CreateCardRoomRes;
      case 20003: return EntryRoomReq;
      case 20004: return EntryRoomRes;
      case 30001: return ErrorResponse;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Action>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Action> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Action>() {
          public Action findValueByNumber(int number) {
            return Action.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.roje.game.message.action.ActionOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final Action[] VALUES = values();

  public static Action valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Action(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Action)
}

