// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action.proto

package com.roje.game.message.action;

/**
 * Protobuf enum {@code Action}
 */
public enum Action
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>snap = 0;</code>
   */
  snap(0),
  /**
   * <code>ServerRegReq = 1001;</code>
   */
  ServerRegReq(1001),
  /**
   * <code>ServerRegRes = 1002;</code>
   */
  ServerRegRes(1002),
  /**
   * <code>ServerUpdateReq = 1003;</code>
   */
  ServerUpdateReq(1003),
  /**
   * <code>ServerUpdateRes = 1004;</code>
   */
  ServerUpdateRes(1004),
  /**
   * <code>PubGateConnected = 2001;</code>
   */
  PubGateConnected(2001),
  /**
   * <code>PubErrorMessage = 2002;</code>
   */
  PubErrorMessage(2002),
  /**
   * <code>LoginReq = 10001;</code>
   */
  LoginReq(10001),
  /**
   * <code>LoginRes = 10002;</code>
   */
  LoginRes(10002),
  /**
   * <code>HeartBeatReq = 10003;</code>
   */
  HeartBeatReq(10003),
  /**
   * <code>HeartBeatRes = 10004;</code>
   */
  HeartBeatRes(10004),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>snap = 0;</code>
   */
  public static final int snap_VALUE = 0;
  /**
   * <code>ServerRegReq = 1001;</code>
   */
  public static final int ServerRegReq_VALUE = 1001;
  /**
   * <code>ServerRegRes = 1002;</code>
   */
  public static final int ServerRegRes_VALUE = 1002;
  /**
   * <code>ServerUpdateReq = 1003;</code>
   */
  public static final int ServerUpdateReq_VALUE = 1003;
  /**
   * <code>ServerUpdateRes = 1004;</code>
   */
  public static final int ServerUpdateRes_VALUE = 1004;
  /**
   * <code>PubGateConnected = 2001;</code>
   */
  public static final int PubGateConnected_VALUE = 2001;
  /**
   * <code>PubErrorMessage = 2002;</code>
   */
  public static final int PubErrorMessage_VALUE = 2002;
  /**
   * <code>LoginReq = 10001;</code>
   */
  public static final int LoginReq_VALUE = 10001;
  /**
   * <code>LoginRes = 10002;</code>
   */
  public static final int LoginRes_VALUE = 10002;
  /**
   * <code>HeartBeatReq = 10003;</code>
   */
  public static final int HeartBeatReq_VALUE = 10003;
  /**
   * <code>HeartBeatRes = 10004;</code>
   */
  public static final int HeartBeatRes_VALUE = 10004;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Action valueOf(int value) {
    return forNumber(value);
  }

  public static Action forNumber(int value) {
    switch (value) {
      case 0: return snap;
      case 1001: return ServerRegReq;
      case 1002: return ServerRegRes;
      case 1003: return ServerUpdateReq;
      case 1004: return ServerUpdateRes;
      case 2001: return PubGateConnected;
      case 2002: return PubErrorMessage;
      case 10001: return LoginReq;
      case 10002: return LoginRes;
      case 10003: return HeartBeatReq;
      case 10004: return HeartBeatRes;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Action>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Action> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Action>() {
          public Action findValueByNumber(int number) {
            return Action.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.roje.game.message.action.ActionOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final Action[] VALUES = values();

  public static Action valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Action(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Action)
}

