// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action.proto

package com.roje.game.message.action;

public final class ActionOuterClass {
  private ActionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014action.proto*\232\001\n\006Action\022\010\n\004snap\020\000\022\020\n\013S" +
      "ervInfoReq\020\351\007\022\020\n\013ServInfoRes\020\352\007\022\r\n\010Login" +
      "Req\020\221N\022\r\n\010loginRes\020\222N\022\027\n\021CreateCardRoomR" +
      "eq\020\241\234\001\022\026\n\020CreateCarRoomRes\020\242\234\001\022\023\n\rErrorR" +
      "esponse\020\261\352\001B \n\034com.roje.game.message.act" +
      "ionP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
