// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error_message.proto

package com.roje.game.message.error;

/**
 * Protobuf enum {@code ErrorCode}
 */
public enum ErrorCode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UnknownErrType = 0;</code>
   */
  UnknownErrType(0),
  /**
   * <code>HallNotFind = 1;</code>
   */
  HallNotFind(1),
  /**
   * <code>GateNotFind = 2;</code>
   */
  GateNotFind(2),
  /**
   * <code>NotLoginOn = 3;</code>
   */
  NotLoginOn(3),
  /**
   * <code>ConnectReset = 4;</code>
   */
  ConnectReset(4),
  /**
   * <code>RepeatedReq = 5;</code>
   */
  RepeatedReq(5),
  /**
   * <code>AlreadyLogged = 6;</code>
   */
  AlreadyLogged(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UnknownErrType = 0;</code>
   */
  public static final int UnknownErrType_VALUE = 0;
  /**
   * <code>HallNotFind = 1;</code>
   */
  public static final int HallNotFind_VALUE = 1;
  /**
   * <code>GateNotFind = 2;</code>
   */
  public static final int GateNotFind_VALUE = 2;
  /**
   * <code>NotLoginOn = 3;</code>
   */
  public static final int NotLoginOn_VALUE = 3;
  /**
   * <code>ConnectReset = 4;</code>
   */
  public static final int ConnectReset_VALUE = 4;
  /**
   * <code>RepeatedReq = 5;</code>
   */
  public static final int RepeatedReq_VALUE = 5;
  /**
   * <code>AlreadyLogged = 6;</code>
   */
  public static final int AlreadyLogged_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ErrorCode valueOf(int value) {
    return forNumber(value);
  }

  public static ErrorCode forNumber(int value) {
    switch (value) {
      case 0: return UnknownErrType;
      case 1: return HallNotFind;
      case 2: return GateNotFind;
      case 3: return NotLoginOn;
      case 4: return ConnectReset;
      case 5: return RepeatedReq;
      case 6: return AlreadyLogged;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ErrorCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
          public ErrorCode findValueByNumber(int number) {
            return ErrorCode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.roje.game.message.error.ErrorMessageOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ErrorCode[] VALUES = values();

  public static ErrorCode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ErrorCode)
}

