// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginMessage.proto

package com.roje.game.message.login;

public final class LoginMessage {
  private LoginMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code LoginType}
   *
   * <pre>
   *登录类型
   * </pre>
   */
  public enum LoginType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACCOUNT = 1;</code>
     *
     * <pre>
     *账号登录
     * </pre>
     */
    ACCOUNT(0, 1),
    /**
     * <code>WECHAT = 2;</code>
     *
     * <pre>
     *微信登录
     * </pre>
     */
    WECHAT(1, 2),
    ;

    /**
     * <code>ACCOUNT = 1;</code>
     *
     * <pre>
     *账号登录
     * </pre>
     */
    public static final int ACCOUNT_VALUE = 1;
    /**
     * <code>WECHAT = 2;</code>
     *
     * <pre>
     *微信登录
     * </pre>
     */
    public static final int WECHAT_VALUE = 2;


    public final int getNumber() { return value; }

    public static LoginType valueOf(int value) {
      switch (value) {
        case 1: return ACCOUNT;
        case 2: return WECHAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LoginType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LoginType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LoginType>() {
            public LoginType findValueByNumber(int number) {
              return LoginType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.roje.game.message.login.LoginMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final LoginType[] VALUES = values();

    public static LoginType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LoginType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LoginType)
  }

  public interface LoginRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .MID mid = 1 [default = LoginReq];
    /**
     * <code>optional .MID mid = 1 [default = LoginReq];</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    boolean hasMid();
    /**
     * <code>optional .MID mid = 1 [default = LoginReq];</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    com.roje.game.message.Mid.MID getMid();

    // optional string account = 2;
    /**
     * <code>optional string account = 2;</code>
     *
     * <pre>
     *账号
     * </pre>
     */
    boolean hasAccount();
    /**
     * <code>optional string account = 2;</code>
     *
     * <pre>
     *账号
     * </pre>
     */
    java.lang.String getAccount();
    /**
     * <code>optional string account = 2;</code>
     *
     * <pre>
     *账号
     * </pre>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    // optional string password = 3;
    /**
     * <code>optional string password = 3;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 3;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 3;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // optional .LoginType loginType = 4;
    /**
     * <code>optional .LoginType loginType = 4;</code>
     *
     * <pre>
     *登录类型
     * </pre>
     */
    boolean hasLoginType();
    /**
     * <code>optional .LoginType loginType = 4;</code>
     *
     * <pre>
     *登录类型
     * </pre>
     */
    com.roje.game.message.login.LoginMessage.LoginType getLoginType();

    // optional string sessionId = 5;
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID（服务器内部使用）
     * </pre>
     */
    boolean hasSessionId();
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID（服务器内部使用）
     * </pre>
     */
    java.lang.String getSessionId();
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID（服务器内部使用）
     * </pre>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    // optional int32 gateId = 6;
    /**
     * <code>optional int32 gateId = 6;</code>
     *
     * <pre>
     *网关ID（服务器内部使用）
     * </pre>
     */
    boolean hasGateId();
    /**
     * <code>optional int32 gateId = 6;</code>
     *
     * <pre>
     *网关ID（服务器内部使用）
     * </pre>
     */
    int getGateId();

    // optional string ip = 7;
    /**
     * <code>optional string ip = 7;</code>
     *
     * <pre>
     *IP地址（服务器内部使用）
     * </pre>
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 7;</code>
     *
     * <pre>
     *IP地址（服务器内部使用）
     * </pre>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 7;</code>
     *
     * <pre>
     *IP地址（服务器内部使用）
     * </pre>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    // optional int32 version = 8;
    /**
     * <code>optional int32 version = 8;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 8;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    int getVersion();
  }
  /**
   * Protobuf type {@code LoginRequest}
   */
  public static final class LoginRequest extends
      com.google.protobuf.GeneratedMessage
      implements LoginRequestOrBuilder {
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginRequest defaultInstance;
    public static LoginRequest getDefaultInstance() {
      return defaultInstance;
    }

    public LoginRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.roje.game.message.Mid.MID value = com.roje.game.message.Mid.MID.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                mid_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              account_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              password_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.roje.game.message.login.LoginMessage.LoginType value = com.roje.game.message.login.LoginMessage.LoginType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                loginType_ = value;
              }
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              sessionId_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              gateId_ = input.readInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              ip_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              version_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.roje.game.message.login.LoginMessage.internal_static_LoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.roje.game.message.login.LoginMessage.internal_static_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.roje.game.message.login.LoginMessage.LoginRequest.class, com.roje.game.message.login.LoginMessage.LoginRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginRequest> PARSER =
        new com.google.protobuf.AbstractParser<LoginRequest>() {
      public LoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .MID mid = 1 [default = LoginReq];
    public static final int MID_FIELD_NUMBER = 1;
    private com.roje.game.message.Mid.MID mid_;
    /**
     * <code>optional .MID mid = 1 [default = LoginReq];</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    public boolean hasMid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .MID mid = 1 [default = LoginReq];</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    public com.roje.game.message.Mid.MID getMid() {
      return mid_;
    }

    // optional string account = 2;
    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private java.lang.Object account_;
    /**
     * <code>optional string account = 2;</code>
     *
     * <pre>
     *账号
     * </pre>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string account = 2;</code>
     *
     * <pre>
     *账号
     * </pre>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string account = 2;</code>
     *
     * <pre>
     *账号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string password = 3;
    public static final int PASSWORD_FIELD_NUMBER = 3;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 3;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string password = 3;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 3;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .LoginType loginType = 4;
    public static final int LOGINTYPE_FIELD_NUMBER = 4;
    private com.roje.game.message.login.LoginMessage.LoginType loginType_;
    /**
     * <code>optional .LoginType loginType = 4;</code>
     *
     * <pre>
     *登录类型
     * </pre>
     */
    public boolean hasLoginType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .LoginType loginType = 4;</code>
     *
     * <pre>
     *登录类型
     * </pre>
     */
    public com.roje.game.message.login.LoginMessage.LoginType getLoginType() {
      return loginType_;
    }

    // optional string sessionId = 5;
    public static final int SESSIONID_FIELD_NUMBER = 5;
    private java.lang.Object sessionId_;
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID（服务器内部使用）
     * </pre>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID（服务器内部使用）
     * </pre>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID（服务器内部使用）
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 gateId = 6;
    public static final int GATEID_FIELD_NUMBER = 6;
    private int gateId_;
    /**
     * <code>optional int32 gateId = 6;</code>
     *
     * <pre>
     *网关ID（服务器内部使用）
     * </pre>
     */
    public boolean hasGateId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 gateId = 6;</code>
     *
     * <pre>
     *网关ID（服务器内部使用）
     * </pre>
     */
    public int getGateId() {
      return gateId_;
    }

    // optional string ip = 7;
    public static final int IP_FIELD_NUMBER = 7;
    private java.lang.Object ip_;
    /**
     * <code>optional string ip = 7;</code>
     *
     * <pre>
     *IP地址（服务器内部使用）
     * </pre>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string ip = 7;</code>
     *
     * <pre>
     *IP地址（服务器内部使用）
     * </pre>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ip = 7;</code>
     *
     * <pre>
     *IP地址（服务器内部使用）
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 version = 8;
    public static final int VERSION_FIELD_NUMBER = 8;
    private int version_;
    /**
     * <code>optional int32 version = 8;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 version = 8;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    private void initFields() {
      mid_ = com.roje.game.message.Mid.MID.LoginReq;
      account_ = "";
      password_ = "";
      loginType_ = com.roje.game.message.login.LoginMessage.LoginType.ACCOUNT;
      sessionId_ = "";
      gateId_ = 0;
      ip_ = "";
      version_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, mid_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, loginType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, gateId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getIpBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, version_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, mid_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, loginType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, gateId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getIpBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, version_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.roje.game.message.login.LoginMessage.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.roje.game.message.login.LoginMessage.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.roje.game.message.login.LoginMessage.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.roje.game.message.login.LoginMessage.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.roje.game.message.login.LoginMessage.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.roje.game.message.login.LoginMessage.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.roje.game.message.login.LoginMessage.LoginRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.roje.game.message.login.LoginMessage.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.roje.game.message.login.LoginMessage.internal_static_LoginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.roje.game.message.login.LoginMessage.internal_static_LoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.roje.game.message.login.LoginMessage.LoginRequest.class, com.roje.game.message.login.LoginMessage.LoginRequest.Builder.class);
      }

      // Construct using com.roje.game.message.login.LoginMessage.LoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mid_ = com.roje.game.message.Mid.MID.LoginReq;
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        loginType_ = com.roje.game.message.login.LoginMessage.LoginType.ACCOUNT;
        bitField0_ = (bitField0_ & ~0x00000008);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        gateId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.roje.game.message.login.LoginMessage.internal_static_LoginRequest_descriptor;
      }

      public com.roje.game.message.login.LoginMessage.LoginRequest getDefaultInstanceForType() {
        return com.roje.game.message.login.LoginMessage.LoginRequest.getDefaultInstance();
      }

      public com.roje.game.message.login.LoginMessage.LoginRequest build() {
        com.roje.game.message.login.LoginMessage.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.roje.game.message.login.LoginMessage.LoginRequest buildPartial() {
        com.roje.game.message.login.LoginMessage.LoginRequest result = new com.roje.game.message.login.LoginMessage.LoginRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mid_ = mid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.loginType_ = loginType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.gateId_ = gateId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.version_ = version_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.roje.game.message.login.LoginMessage.LoginRequest) {
          return mergeFrom((com.roje.game.message.login.LoginMessage.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.roje.game.message.login.LoginMessage.LoginRequest other) {
        if (other == com.roje.game.message.login.LoginMessage.LoginRequest.getDefaultInstance()) return this;
        if (other.hasMid()) {
          setMid(other.getMid());
        }
        if (other.hasAccount()) {
          bitField0_ |= 0x00000002;
          account_ = other.account_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000004;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasLoginType()) {
          setLoginType(other.getLoginType());
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000010;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasGateId()) {
          setGateId(other.getGateId());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000040;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.roje.game.message.login.LoginMessage.LoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.roje.game.message.login.LoginMessage.LoginRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .MID mid = 1 [default = LoginReq];
      private com.roje.game.message.Mid.MID mid_ = com.roje.game.message.Mid.MID.LoginReq;
      /**
       * <code>optional .MID mid = 1 [default = LoginReq];</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public boolean hasMid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .MID mid = 1 [default = LoginReq];</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public com.roje.game.message.Mid.MID getMid() {
        return mid_;
      }
      /**
       * <code>optional .MID mid = 1 [default = LoginReq];</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public Builder setMid(com.roje.game.message.Mid.MID value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        mid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .MID mid = 1 [default = LoginReq];</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public Builder clearMid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mid_ = com.roje.game.message.Mid.MID.LoginReq;
        onChanged();
        return this;
      }

      // optional string account = 2;
      private java.lang.Object account_ = "";
      /**
       * <code>optional string account = 2;</code>
       *
       * <pre>
       *账号
       * </pre>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string account = 2;</code>
       *
       * <pre>
       *账号
       * </pre>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string account = 2;</code>
       *
       * <pre>
       *账号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account = 2;</code>
       *
       * <pre>
       *账号
       * </pre>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 2;</code>
       *
       * <pre>
       *账号
       * </pre>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 2;</code>
       *
       * <pre>
       *账号
       * </pre>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }

      // optional string password = 3;
      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 3;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string password = 3;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }

      // optional .LoginType loginType = 4;
      private com.roje.game.message.login.LoginMessage.LoginType loginType_ = com.roje.game.message.login.LoginMessage.LoginType.ACCOUNT;
      /**
       * <code>optional .LoginType loginType = 4;</code>
       *
       * <pre>
       *登录类型
       * </pre>
       */
      public boolean hasLoginType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .LoginType loginType = 4;</code>
       *
       * <pre>
       *登录类型
       * </pre>
       */
      public com.roje.game.message.login.LoginMessage.LoginType getLoginType() {
        return loginType_;
      }
      /**
       * <code>optional .LoginType loginType = 4;</code>
       *
       * <pre>
       *登录类型
       * </pre>
       */
      public Builder setLoginType(com.roje.game.message.login.LoginMessage.LoginType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        loginType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .LoginType loginType = 4;</code>
       *
       * <pre>
       *登录类型
       * </pre>
       */
      public Builder clearLoginType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        loginType_ = com.roje.game.message.login.LoginMessage.LoginType.ACCOUNT;
        onChanged();
        return this;
      }

      // optional string sessionId = 5;
      private java.lang.Object sessionId_ = "";
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID（服务器内部使用）
       * </pre>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID（服务器内部使用）
       * </pre>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID（服务器内部使用）
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID（服务器内部使用）
       * </pre>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID（服务器内部使用）
       * </pre>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID（服务器内部使用）
       * </pre>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sessionId_ = value;
        onChanged();
        return this;
      }

      // optional int32 gateId = 6;
      private int gateId_ ;
      /**
       * <code>optional int32 gateId = 6;</code>
       *
       * <pre>
       *网关ID（服务器内部使用）
       * </pre>
       */
      public boolean hasGateId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 gateId = 6;</code>
       *
       * <pre>
       *网关ID（服务器内部使用）
       * </pre>
       */
      public int getGateId() {
        return gateId_;
      }
      /**
       * <code>optional int32 gateId = 6;</code>
       *
       * <pre>
       *网关ID（服务器内部使用）
       * </pre>
       */
      public Builder setGateId(int value) {
        bitField0_ |= 0x00000020;
        gateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gateId = 6;</code>
       *
       * <pre>
       *网关ID（服务器内部使用）
       * </pre>
       */
      public Builder clearGateId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        gateId_ = 0;
        onChanged();
        return this;
      }

      // optional string ip = 7;
      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 7;</code>
       *
       * <pre>
       *IP地址（服务器内部使用）
       * </pre>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string ip = 7;</code>
       *
       * <pre>
       *IP地址（服务器内部使用）
       * </pre>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 7;</code>
       *
       * <pre>
       *IP地址（服务器内部使用）
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 7;</code>
       *
       * <pre>
       *IP地址（服务器内部使用）
       * </pre>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 7;</code>
       *
       * <pre>
       *IP地址（服务器内部使用）
       * </pre>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 7;</code>
       *
       * <pre>
       *IP地址（服务器内部使用）
       * </pre>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        ip_ = value;
        onChanged();
        return this;
      }

      // optional int32 version = 8;
      private int version_ ;
      /**
       * <code>optional int32 version = 8;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 version = 8;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 8;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000080;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 8;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000080);
        version_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LoginRequest)
    }

    static {
      defaultInstance = new LoginRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LoginRequest)
  }

  public interface LoginResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .MID mid = 1 [default = LoginRes];
    /**
     * <code>optional .MID mid = 1 [default = LoginRes];</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    boolean hasMid();
    /**
     * <code>optional .MID mid = 1 [default = LoginRes];</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    com.roje.game.message.Mid.MID getMid();

    // optional bool ok = 2;
    /**
     * <code>optional bool ok = 2;</code>
     *
     * <pre>
     *请求是否发送成功
     * </pre>
     */
    boolean hasOk();
    /**
     * <code>optional bool ok = 2;</code>
     *
     * <pre>
     *请求是否发送成功
     * </pre>
     */
    boolean getOk();

    // optional int64 uid = 3;
    /**
     * <code>optional int64 uid = 3;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    boolean hasUid();
    /**
     * <code>optional int64 uid = 3;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    long getUid();

    // optional int64 rid = 4;
    /**
     * <code>optional int64 rid = 4;</code>
     *
     * <pre>
     *角色ID
     * </pre>
     */
    boolean hasRid();
    /**
     * <code>optional int64 rid = 4;</code>
     *
     * <pre>
     *角色ID
     * </pre>
     */
    long getRid();

    // optional string sessionId = 5;
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID
     * </pre>
     */
    boolean hasSessionId();
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID
     * </pre>
     */
    java.lang.String getSessionId();
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();
  }
  /**
   * Protobuf type {@code LoginResponse}
   */
  public static final class LoginResponse extends
      com.google.protobuf.GeneratedMessage
      implements LoginResponseOrBuilder {
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginResponse defaultInstance;
    public static LoginResponse getDefaultInstance() {
      return defaultInstance;
    }

    public LoginResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.roje.game.message.Mid.MID value = com.roje.game.message.Mid.MID.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                mid_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ok_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              uid_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              rid_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              sessionId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.roje.game.message.login.LoginMessage.internal_static_LoginResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.roje.game.message.login.LoginMessage.internal_static_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.roje.game.message.login.LoginMessage.LoginResponse.class, com.roje.game.message.login.LoginMessage.LoginResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginResponse> PARSER =
        new com.google.protobuf.AbstractParser<LoginResponse>() {
      public LoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .MID mid = 1 [default = LoginRes];
    public static final int MID_FIELD_NUMBER = 1;
    private com.roje.game.message.Mid.MID mid_;
    /**
     * <code>optional .MID mid = 1 [default = LoginRes];</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    public boolean hasMid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .MID mid = 1 [default = LoginRes];</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    public com.roje.game.message.Mid.MID getMid() {
      return mid_;
    }

    // optional bool ok = 2;
    public static final int OK_FIELD_NUMBER = 2;
    private boolean ok_;
    /**
     * <code>optional bool ok = 2;</code>
     *
     * <pre>
     *请求是否发送成功
     * </pre>
     */
    public boolean hasOk() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool ok = 2;</code>
     *
     * <pre>
     *请求是否发送成功
     * </pre>
     */
    public boolean getOk() {
      return ok_;
    }

    // optional int64 uid = 3;
    public static final int UID_FIELD_NUMBER = 3;
    private long uid_;
    /**
     * <code>optional int64 uid = 3;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 uid = 3;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public long getUid() {
      return uid_;
    }

    // optional int64 rid = 4;
    public static final int RID_FIELD_NUMBER = 4;
    private long rid_;
    /**
     * <code>optional int64 rid = 4;</code>
     *
     * <pre>
     *角色ID
     * </pre>
     */
    public boolean hasRid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 rid = 4;</code>
     *
     * <pre>
     *角色ID
     * </pre>
     */
    public long getRid() {
      return rid_;
    }

    // optional string sessionId = 5;
    public static final int SESSIONID_FIELD_NUMBER = 5;
    private java.lang.Object sessionId_;
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID
     * </pre>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID
     * </pre>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sessionId = 5;</code>
     *
     * <pre>
     *会话ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      mid_ = com.roje.game.message.Mid.MID.LoginRes;
      ok_ = false;
      uid_ = 0L;
      rid_ = 0L;
      sessionId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, mid_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, ok_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, uid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, rid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSessionIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, mid_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, ok_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, uid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, rid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSessionIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.roje.game.message.login.LoginMessage.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.roje.game.message.login.LoginMessage.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.roje.game.message.login.LoginMessage.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.roje.game.message.login.LoginMessage.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.roje.game.message.login.LoginMessage.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.roje.game.message.login.LoginMessage.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.roje.game.message.login.LoginMessage.LoginResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.roje.game.message.login.LoginMessage.LoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.roje.game.message.login.LoginMessage.internal_static_LoginResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.roje.game.message.login.LoginMessage.internal_static_LoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.roje.game.message.login.LoginMessage.LoginResponse.class, com.roje.game.message.login.LoginMessage.LoginResponse.Builder.class);
      }

      // Construct using com.roje.game.message.login.LoginMessage.LoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mid_ = com.roje.game.message.Mid.MID.LoginRes;
        bitField0_ = (bitField0_ & ~0x00000001);
        ok_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        rid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.roje.game.message.login.LoginMessage.internal_static_LoginResponse_descriptor;
      }

      public com.roje.game.message.login.LoginMessage.LoginResponse getDefaultInstanceForType() {
        return com.roje.game.message.login.LoginMessage.LoginResponse.getDefaultInstance();
      }

      public com.roje.game.message.login.LoginMessage.LoginResponse build() {
        com.roje.game.message.login.LoginMessage.LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.roje.game.message.login.LoginMessage.LoginResponse buildPartial() {
        com.roje.game.message.login.LoginMessage.LoginResponse result = new com.roje.game.message.login.LoginMessage.LoginResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mid_ = mid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ok_ = ok_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rid_ = rid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sessionId_ = sessionId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.roje.game.message.login.LoginMessage.LoginResponse) {
          return mergeFrom((com.roje.game.message.login.LoginMessage.LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.roje.game.message.login.LoginMessage.LoginResponse other) {
        if (other == com.roje.game.message.login.LoginMessage.LoginResponse.getDefaultInstance()) return this;
        if (other.hasMid()) {
          setMid(other.getMid());
        }
        if (other.hasOk()) {
          setOk(other.getOk());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasRid()) {
          setRid(other.getRid());
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000010;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.roje.game.message.login.LoginMessage.LoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.roje.game.message.login.LoginMessage.LoginResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .MID mid = 1 [default = LoginRes];
      private com.roje.game.message.Mid.MID mid_ = com.roje.game.message.Mid.MID.LoginRes;
      /**
       * <code>optional .MID mid = 1 [default = LoginRes];</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public boolean hasMid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .MID mid = 1 [default = LoginRes];</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public com.roje.game.message.Mid.MID getMid() {
        return mid_;
      }
      /**
       * <code>optional .MID mid = 1 [default = LoginRes];</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public Builder setMid(com.roje.game.message.Mid.MID value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        mid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .MID mid = 1 [default = LoginRes];</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public Builder clearMid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mid_ = com.roje.game.message.Mid.MID.LoginRes;
        onChanged();
        return this;
      }

      // optional bool ok = 2;
      private boolean ok_ ;
      /**
       * <code>optional bool ok = 2;</code>
       *
       * <pre>
       *请求是否发送成功
       * </pre>
       */
      public boolean hasOk() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool ok = 2;</code>
       *
       * <pre>
       *请求是否发送成功
       * </pre>
       */
      public boolean getOk() {
        return ok_;
      }
      /**
       * <code>optional bool ok = 2;</code>
       *
       * <pre>
       *请求是否发送成功
       * </pre>
       */
      public Builder setOk(boolean value) {
        bitField0_ |= 0x00000002;
        ok_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool ok = 2;</code>
       *
       * <pre>
       *请求是否发送成功
       * </pre>
       */
      public Builder clearOk() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ok_ = false;
        onChanged();
        return this;
      }

      // optional int64 uid = 3;
      private long uid_ ;
      /**
       * <code>optional int64 uid = 3;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 uid = 3;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>optional int64 uid = 3;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000004;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 uid = 3;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uid_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 rid = 4;
      private long rid_ ;
      /**
       * <code>optional int64 rid = 4;</code>
       *
       * <pre>
       *角色ID
       * </pre>
       */
      public boolean hasRid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 rid = 4;</code>
       *
       * <pre>
       *角色ID
       * </pre>
       */
      public long getRid() {
        return rid_;
      }
      /**
       * <code>optional int64 rid = 4;</code>
       *
       * <pre>
       *角色ID
       * </pre>
       */
      public Builder setRid(long value) {
        bitField0_ |= 0x00000008;
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 rid = 4;</code>
       *
       * <pre>
       *角色ID
       * </pre>
       */
      public Builder clearRid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rid_ = 0L;
        onChanged();
        return this;
      }

      // optional string sessionId = 5;
      private java.lang.Object sessionId_ = "";
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID
       * </pre>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID
       * </pre>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID
       * </pre>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID
       * </pre>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 5;</code>
       *
       * <pre>
       *会话ID
       * </pre>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sessionId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LoginResponse)
    }

    static {
      defaultInstance = new LoginResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LoginResponse)
  }

  public interface LoseConnectionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .MID mid = 1 [default = LoseConntionReq];
    /**
     * <code>optional .MID mid = 1 [default = LoseConntionReq];</code>
     */
    boolean hasMid();
    /**
     * <code>optional .MID mid = 1 [default = LoseConntionReq];</code>
     */
    com.roje.game.message.Mid.MID getMid();

    // optional int64 uid = 2;
    /**
     * <code>optional int64 uid = 2;</code>
     */
    boolean hasUid();
    /**
     * <code>optional int64 uid = 2;</code>
     */
    long getUid();

    // optional int64 rid = 3;
    /**
     * <code>optional int64 rid = 3;</code>
     */
    boolean hasRid();
    /**
     * <code>optional int64 rid = 3;</code>
     */
    long getRid();
  }
  /**
   * Protobuf type {@code LoseConnection}
   */
  public static final class LoseConnection extends
      com.google.protobuf.GeneratedMessage
      implements LoseConnectionOrBuilder {
    // Use LoseConnection.newBuilder() to construct.
    private LoseConnection(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoseConnection(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoseConnection defaultInstance;
    public static LoseConnection getDefaultInstance() {
      return defaultInstance;
    }

    public LoseConnection getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoseConnection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.roje.game.message.Mid.MID value = com.roje.game.message.Mid.MID.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                mid_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              uid_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rid_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.roje.game.message.login.LoginMessage.internal_static_LoseConnection_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.roje.game.message.login.LoginMessage.internal_static_LoseConnection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.roje.game.message.login.LoginMessage.LoseConnection.class, com.roje.game.message.login.LoginMessage.LoseConnection.Builder.class);
    }

    public static com.google.protobuf.Parser<LoseConnection> PARSER =
        new com.google.protobuf.AbstractParser<LoseConnection>() {
      public LoseConnection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoseConnection(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoseConnection> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .MID mid = 1 [default = LoseConntionReq];
    public static final int MID_FIELD_NUMBER = 1;
    private com.roje.game.message.Mid.MID mid_;
    /**
     * <code>optional .MID mid = 1 [default = LoseConntionReq];</code>
     */
    public boolean hasMid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .MID mid = 1 [default = LoseConntionReq];</code>
     */
    public com.roje.game.message.Mid.MID getMid() {
      return mid_;
    }

    // optional int64 uid = 2;
    public static final int UID_FIELD_NUMBER = 2;
    private long uid_;
    /**
     * <code>optional int64 uid = 2;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 uid = 2;</code>
     */
    public long getUid() {
      return uid_;
    }

    // optional int64 rid = 3;
    public static final int RID_FIELD_NUMBER = 3;
    private long rid_;
    /**
     * <code>optional int64 rid = 3;</code>
     */
    public boolean hasRid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 rid = 3;</code>
     */
    public long getRid() {
      return rid_;
    }

    private void initFields() {
      mid_ = com.roje.game.message.Mid.MID.LoseConntionReq;
      uid_ = 0L;
      rid_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, mid_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, rid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, mid_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, rid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.roje.game.message.login.LoginMessage.LoseConnection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.roje.game.message.login.LoginMessage.LoseConnection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoseConnection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.roje.game.message.login.LoginMessage.LoseConnection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoseConnection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.roje.game.message.login.LoginMessage.LoseConnection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoseConnection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.roje.game.message.login.LoginMessage.LoseConnection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.roje.game.message.login.LoginMessage.LoseConnection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.roje.game.message.login.LoginMessage.LoseConnection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.roje.game.message.login.LoginMessage.LoseConnection prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoseConnection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.roje.game.message.login.LoginMessage.LoseConnectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.roje.game.message.login.LoginMessage.internal_static_LoseConnection_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.roje.game.message.login.LoginMessage.internal_static_LoseConnection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.roje.game.message.login.LoginMessage.LoseConnection.class, com.roje.game.message.login.LoginMessage.LoseConnection.Builder.class);
      }

      // Construct using com.roje.game.message.login.LoginMessage.LoseConnection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mid_ = com.roje.game.message.Mid.MID.LoseConntionReq;
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        rid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.roje.game.message.login.LoginMessage.internal_static_LoseConnection_descriptor;
      }

      public com.roje.game.message.login.LoginMessage.LoseConnection getDefaultInstanceForType() {
        return com.roje.game.message.login.LoginMessage.LoseConnection.getDefaultInstance();
      }

      public com.roje.game.message.login.LoginMessage.LoseConnection build() {
        com.roje.game.message.login.LoginMessage.LoseConnection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.roje.game.message.login.LoginMessage.LoseConnection buildPartial() {
        com.roje.game.message.login.LoginMessage.LoseConnection result = new com.roje.game.message.login.LoginMessage.LoseConnection(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mid_ = mid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rid_ = rid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.roje.game.message.login.LoginMessage.LoseConnection) {
          return mergeFrom((com.roje.game.message.login.LoginMessage.LoseConnection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.roje.game.message.login.LoginMessage.LoseConnection other) {
        if (other == com.roje.game.message.login.LoginMessage.LoseConnection.getDefaultInstance()) return this;
        if (other.hasMid()) {
          setMid(other.getMid());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasRid()) {
          setRid(other.getRid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.roje.game.message.login.LoginMessage.LoseConnection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.roje.game.message.login.LoginMessage.LoseConnection) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .MID mid = 1 [default = LoseConntionReq];
      private com.roje.game.message.Mid.MID mid_ = com.roje.game.message.Mid.MID.LoseConntionReq;
      /**
       * <code>optional .MID mid = 1 [default = LoseConntionReq];</code>
       */
      public boolean hasMid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .MID mid = 1 [default = LoseConntionReq];</code>
       */
      public com.roje.game.message.Mid.MID getMid() {
        return mid_;
      }
      /**
       * <code>optional .MID mid = 1 [default = LoseConntionReq];</code>
       */
      public Builder setMid(com.roje.game.message.Mid.MID value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        mid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .MID mid = 1 [default = LoseConntionReq];</code>
       */
      public Builder clearMid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mid_ = com.roje.game.message.Mid.MID.LoseConntionReq;
        onChanged();
        return this;
      }

      // optional int64 uid = 2;
      private long uid_ ;
      /**
       * <code>optional int64 uid = 2;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 uid = 2;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>optional int64 uid = 2;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000002;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 uid = 2;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 rid = 3;
      private long rid_ ;
      /**
       * <code>optional int64 rid = 3;</code>
       */
      public boolean hasRid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 rid = 3;</code>
       */
      public long getRid() {
        return rid_;
      }
      /**
       * <code>optional int64 rid = 3;</code>
       */
      public Builder setRid(long value) {
        bitField0_ |= 0x00000004;
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 rid = 3;</code>
       */
      public Builder clearRid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rid_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LoseConnection)
    }

    static {
      defaultInstance = new LoseConnection(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LoseConnection)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LoseConnection_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoseConnection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LoginMessage.proto\032\tMid.proto\"\255\001\n\014Logi" +
      "nRequest\022\033\n\003mid\030\001 \001(\0162\004.MID:\010LoginReq\022\017\n" +
      "\007account\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\035\n\tlogi" +
      "nType\030\004 \001(\0162\n.LoginType\022\021\n\tsessionId\030\005 \001" +
      "(\t\022\016\n\006gateId\030\006 \001(\005\022\n\n\002ip\030\007 \001(\t\022\017\n\007versio" +
      "n\030\010 \001(\005\"e\n\rLoginResponse\022\033\n\003mid\030\001 \001(\0162\004." +
      "MID:\010LoginRes\022\n\n\002ok\030\002 \001(\010\022\013\n\003uid\030\003 \001(\003\022\013" +
      "\n\003rid\030\004 \001(\003\022\021\n\tsessionId\030\005 \001(\t\"N\n\016LoseCo" +
      "nnection\022\"\n\003mid\030\001 \001(\0162\004.MID:\017LoseConntio" +
      "nReq\022\013\n\003uid\030\002 \001(\003\022\013\n\003rid\030\003 \001(\003*$\n\tLoginT",
      "ype\022\013\n\007ACCOUNT\020\001\022\n\n\006WECHAT\020\002B\035\n\033com.roje" +
      ".game.message.login"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_LoginRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_LoginRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LoginRequest_descriptor,
              new java.lang.String[] { "Mid", "Account", "Password", "LoginType", "SessionId", "GateId", "Ip", "Version", });
          internal_static_LoginResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_LoginResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LoginResponse_descriptor,
              new java.lang.String[] { "Mid", "Ok", "Uid", "Rid", "SessionId", });
          internal_static_LoseConnection_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_LoseConnection_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LoseConnection_descriptor,
              new java.lang.String[] { "Mid", "Uid", "Rid", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.roje.game.message.Mid.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
