// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.roje.game.message.login;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string account = 1;</code>
   */
  java.lang.String getAccount();
  /**
   * <code>string account = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>string gameToken = 2;</code>
   */
  java.lang.String getGameToken();
  /**
   * <code>string gameToken = 2;</code>
   */
  com.google.protobuf.ByteString
      getGameTokenBytes();
}
