// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart_beat.proto

package com.roje.game.message.heart_beat;

public interface HeartBeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartBeatRequest)
    com.google.protobuf.MessageOrBuilder {
}
