// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package com.roje.game.message.broadcast;

public final class Broadcast {
  private Broadcast() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GateConnected_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GateConnected_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017broadcast.proto\"5\n\rGateConnected\022\n\n\002id" +
      "\030\001 \001(\005\022\n\n\002ip\030\002 \001(\t\022\014\n\004prot\030\003 \001(\005B#\n\037com." +
      "roje.game.message.broadcastP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GateConnected_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GateConnected_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GateConnected_descriptor,
        new java.lang.String[] { "Id", "Ip", "Prot", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
