// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast.proto

package com.roje.game.message.broadcast;

public interface GateConnectedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GateConnected)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string ip = 2;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 prot = 3;</code>
   */
  int getProt();
}
